
FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

COPY requirements_streamlit.txt .
RUN pip install --no-cache-dir -r requirements_streamlit.txt

COPY Streamlit/page.py .
COPY Models/ ./Models/

EXPOSE 8501

CMD ["streamlit", "run", "page.py", "--server.address", "0.0.0.0", "--server.port", "8501"]